name: Facebook Bot Hourly
on:
  schedule:
    - cron: '0 * * * *' # Se lance toutes les heures
  workflow_dispatch: # Pour le lancer à la main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install facebook-sdk feedparser beautifulsoup4
      - run: python bot_actu.py
